//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samost.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Samost.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///	&lt;client name=&quot;Иванов А.А.&quot; percentBonus=&quot;2&quot; fixBonus=&quot;0&quot;&gt;
        ///		&lt;deposit type=&quot;1&quot;&gt;
        ///			&lt;payment date=&quot;01.01.2016&quot; sum=&quot;5000&quot;/&gt;
        ///			&lt;payment date=&quot;01.04.2016&quot; sum=&quot;2000&quot;/&gt;
        ///		&lt;/deposit&gt;
        ///		&lt;deposit type=&quot;2&quot; &gt;
        ///			&lt;payment date=&quot;01.01.2016&quot; sum=&quot;4000&quot;/&gt;
        ///		&lt;/deposit&gt;
        ///	&lt;/client&gt;
        ///	&lt;client name=&quot;Петров В.В.&quot; percentBonus=&quot;0&quot; fixBonus=&quot;500&quot;&gt;
        ///		&lt;deposit type=&quot;2&quot;&gt;
        ///			&lt;payment date=&quot;01.01.2016&quot; sum=&quot;4000&quot;/&gt;
        ///		&lt;/deposit&gt;
        ///		&lt;deposit type=&quot;3&quot;&gt;
        ///			&lt;payment date=&quot;01.01 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string clients {
            get {
                return ResourceManager.GetString("clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;deposit key=&quot;1&quot; name=&quot;Юбилейный&quot; percent=&quot;10&quot; /&gt;
        ///	&lt;deposit key=&quot;2&quot; name=&quot;Пенсионный&quot; percent=&quot;15&quot; /&gt;
        ///	&lt;deposit key=&quot;3&quot; name=&quot;Универсальный&quot; percent=&quot;7&quot; /&gt;
        ///&lt;/root&gt;.
        /// </summary>
        internal static string deposits {
            get {
                return ResourceManager.GetString("deposits", resourceCulture);
            }
        }
    }
}
